import * as schema from './sqlite-schema';

export interface SqliteTableDefinition {
  name: string;
  sql: string;
}

/** Current base schema. Historical migrations remain responsible for upgrading existing databases. */
export const sqliteTableDefinitions: readonly SqliteTableDefinition[] = [
  { name: 'settings', sql: schema.createSettingsTableSQL },
  { name: 'settings_migrations', sql: schema.createSettingsMigrationsTableSQL },
  { name: 'audit_logs', sql: schema.createAuditLogsTableSQL },
  { name: 'notification_settings', sql: schema.createNotificationSettingsTableSQL },
  { name: 'users', sql: schema.createUsersTableSQL },
  { name: 'passkeys', sql: schema.createPasskeysTableSQL },
  { name: 'proxies', sql: schema.createProxiesTableSQL },
  { name: 'ssh_keys', sql: schema.createSshKeysTableSQL },
  { name: 'connections', sql: schema.createConnectionsTableSQL },
  { name: 'tags', sql: schema.createTagsTableSQL },
  { name: 'connection_tags', sql: schema.createConnectionTagsTableSQL },
  { name: 'ip_blacklist', sql: schema.createIpBlacklistTableSQL },
  { name: 'command_history', sql: schema.createCommandHistoryTableSQL },
  { name: 'path_history', sql: schema.createPathHistoryTableSQL },
  { name: 'quick_commands', sql: schema.createQuickCommandsTableSQL },
  { name: 'quick_command_tags', sql: schema.createQuickCommandTagsTableSQL },
  { name: 'quick_command_tag_associations', sql: schema.createQuickCommandTagAssociationsTableSQL },
  { name: 'favorite_paths', sql: schema.createFavoritePathsTableSQL },
  { name: 'terminal_themes', sql: schema.createTerminalThemesTableSQL },
  { name: 'appearance_settings', sql: schema.createAppearanceSettingsTableSQL },
  { name: 'agent_apps', sql: schema.createAgentAppsTableSQL },
  { name: 'agent_app_grants', sql: schema.createAgentAppGrantsTableSQL },
  { name: 'agent_app_storage', sql: schema.createAgentAppStorageTableSQL },
  { name: 'agent_settings', sql: schema.createAgentSettingsTableSQL },
  { name: 'agent_hard_limit_confirmations', sql: schema.createAgentHardLimitConfirmationsTableSQL },
  { name: 'agent_target_denylist', sql: schema.createAgentTargetDenylistTableSQL },
  { name: 'agent_target_denylist_meta', sql: schema.createAgentTargetDenylistMetaTableSQL },
  { name: 'ai_providers', sql: schema.createAiProvidersTableSQL },
  { name: 'ai_artifacts', sql: schema.createAiArtifactsTableSQL },
  { name: 'agent_quota_usage', sql: schema.createAgentQuotaUsageTableSQL },
  { name: 'ai_threads', sql: schema.createAiThreadsTableSQL },
  { name: 'agent_runs', sql: schema.createAgentRunsTableSQL },
  { name: 'ai_thread_entries', sql: schema.createAiThreadEntriesTableSQL },
  { name: 'agent_artifact_links', sql: schema.createAgentArtifactLinksTableSQL },
  { name: 'agent_artifact_grants', sql: schema.createAgentArtifactGrantsTableSQL },
  { name: 'agent_artifact_cleanup_confirmations', sql: schema.createAgentArtifactCleanupConfirmationsTableSQL },
  { name: 'ai_context_digests', sql: schema.createAiContextDigestsTableSQL },
  { name: 'ai_memories', sql: schema.createAiMemoriesTableSQL },
  { name: 'agent_runtimes', sql: schema.createAgentRuntimesTableSQL },
  { name: 'agent_steps', sql: schema.createAgentStepsTableSQL },
  { name: 'agent_model_attempts', sql: schema.createAgentModelAttemptsTableSQL },
  { name: 'agent_tool_calls', sql: schema.createAgentToolCallsTableSQL },
  { name: 'agent_events', sql: schema.createAgentEventsTableSQL },
  { name: 'agent_host_events', sql: schema.createAgentHostEventsTableSQL },
  { name: 'agent_commands', sql: schema.createAgentCommandsTableSQL },
  { name: 'agent_checkpoints', sql: schema.createAgentCheckpointsTableSQL },
  { name: 'agent_approvals', sql: schema.createAgentApprovalsTableSQL },
  { name: 'agent_resource_fences', sql: schema.createAgentResourceFencesTableSQL },
  { name: 'agent_leases', sql: schema.createAgentLeasesTableSQL },
  { name: 'agent_resource_quarantine', sql: schema.createAgentResourceQuarantineTableSQL },
  { name: 'agent_workspaces', sql: schema.createAgentWorkspacesTableSQL },
  { name: 'agent_workspace_runtime_commands', sql: schema.createAgentWorkspaceRuntimeCommandsTableSQL },
  { name: 'agent_integrations', sql: schema.createAgentIntegrationsTableSQL },
  { name: 'agent_workspace_runtime_confirmations', sql: schema.createAgentWorkspaceRuntimeConfirmationsTableSQL },
  { name: 'agent_delegations', sql: schema.createAgentDelegationsTableSQL },
  { name: 'agent_mailbox_cursors', sql: schema.createAgentMailboxCursorsTableSQL },
  { name: 'agent_messages', sql: schema.createAgentMessagesTableSQL },
  { name: 'agent_scheduler_work', sql: schema.createAgentSchedulerWorkTableSQL },
  { name: 'agent_delegation_edges', sql: schema.createAgentDelegationEdgesTableSQL },
  { name: 'agent_shared_facts', sql: schema.createAgentSharedFactsTableSQL },
  { name: 'agent_memory_import_confirmations', sql: schema.createAgentMemoryImportConfirmationsTableSQL },
  { name: 'agent_publisher_keys', sql: schema.createAgentPublisherKeysTableSQL },
  { name: 'agent_plugin_stages', sql: schema.createAgentPluginStagesTableSQL },
  { name: 'agent_plugin_versions', sql: schema.createAgentPluginVersionsTableSQL },
  { name: 'agent_plugin_installations', sql: schema.createAgentPluginInstallationsTableSQL },
  { name: 'agent_app_intent_receipts', sql: schema.createAgentAppIntentReceiptsTableSQL },
  { name: 'agent_app_intent_artifact_grants', sql: schema.createAgentAppIntentArtifactGrantsTableSQL },
];
