packages:
  - packages/*
  - test/e2e

catalog:
  '@types/node': ^26.5.0
  axios: ^1.20.0
  dompurify: ^3.4.15
  pino: ^9.14.0
  puppeteer-core: 25.10.0
  tar: 7.5.22

catalogs:
  node-build:
    typescript: ^7.0.2

overrides:
  dompurify: 'catalog:'

allowBuilds:
  bcrypt: true
  'cpu-features@0.0.10': false
  'esbuild@0.28.2': true
  ssh2: true

disallowWorkspaceCycles: true
failIfNoMatch: true
catalogPrune: true
verifyDepsBeforeRun: false
