import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import {
  MODEL_REGISTRY_MAX_RESPONSE_BYTES,
  MODEL_REGISTRY_SOURCE_URL,
  parseModelsDevRegistry,
} from '../src/modules/agent/ai/model-capability-registry-source';

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const output = path.join(repositoryRoot, 'packages/backend/src/modules/agent/ai/model-capability-registry.snapshot.ts');

const main = async (): Promise<void> => {
  const response = await fetch(MODEL_REGISTRY_SOURCE_URL, {
    headers: { accept: 'application/json', 'user-agent': 'nexus-terminal-model-registry-sync' },
  });
  if (!response.ok) throw new Error(`models.dev returned HTTP ${response.status}`);
  const bytes = new Uint8Array(await response.arrayBuffer());
  if (bytes.byteLength > MODEL_REGISTRY_MAX_RESPONSE_BYTES) throw new Error('models.dev response exceeds safe limit');
  const raw = JSON.parse(new TextDecoder().decode(bytes)) as unknown;
  const snapshot = parseModelsDevRegistry(raw, {
    generatedAt: Math.floor(Date.now() / 1000),
    sourceRevision: response.headers.get('etag'),
  });
  const body = `// Generated by packages/backend/tools/sync-model-capability-registry.ts. Do not edit by hand.
// Source: ${MODEL_REGISTRY_SOURCE_URL}

import type { ModelCapabilityRegistrySnapshot } from './model-capability-registry-source';

export const BUILTIN_MODEL_CAPABILITY_REGISTRY = ${JSON.stringify(snapshot, null, 2)} as const satisfies ModelCapabilityRegistrySnapshot;
`;
  const prettierConfig = (await resolveConfig(output)) ?? {};
  const formatted = await format(body, { ...prettierConfig, filepath: output, parser: 'typescript' });
  await fs.writeFile(output, formatted, 'utf8');
  console.log(
    `Wrote ${path.relative(repositoryRoot, output)} with ${Object.keys(snapshot.entries).length} model identifiers.`,
  );
};

void main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
